---SAS formatar campo com 12 caracateres e extrair

DATA PDD.ESTUDO_TITULOS_CANC_201605;

SET PDD.ESTUDO_TITULOS_CANC_201605;
NUM_TITULO1= (PUT(NUM_TITULO,z12.));
NUM_TITULO= SUBSTR(NUM_TITULO1,4,9)*1;
CD_OPERADORA= SUBSTR(NUM_TITULO1,1,3)*1;

RUN;


--- dica beatriz

CONTRATO_CAR=put(put(CONTRATO,z12.),$12.);

CD_OPERADORA=substr(CONTRATO_CAR,1,3)*1;
NUM_CONTRATO=substr(CONTRATO_CAR,4,9)*1;


---- PADRONIZAR CARACTERER
DATA WORK.CANCELAMENTO_&MES_CANCE.;
SET COBRANCA.ESCOB_COMISSAO_&MES_CANCE.;
	CD_OPERADORA=INPUT(SUBSTR(PUT(COD_OPER,z3.),1,3),18.);
	NUM_CONTRATO=INPUT(SUBSTR(PUT(CONTRATO,z9.),1,9),18.);

RUN;

